import { SYSTEM_ID_DD5E } from "../constants";

export const speciesSeed = [
  {
    slug: "aasimar",
    defaultName: "Aasimar",
    defaultDescription: `Aasimar (pronounced AH-sih-mar) are mortals who carry a spark of the Upper Planes within their souls. Whether descended from an angelic being or infused with celestial power, they can fan that spark to bring light, healing, and heavenly fury. Aasimar can arise among any population of mortals. They resemble their parents, but they live for up to 160 years and have features that hint at their celestial heritage, such as metallic freckles, luminous eyes, a halo, or the skin color of an angel (silver, opalescent green, or coppery red). These features start subtle and become obvious when the aasimar learns to reveal their full celestial nature.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
    variant: null,
  },
  {
    slug: "dragonborn",
    defaultName: "Dragonborn",
    defaultDescription: `The ancestors of dragonborn hatched from the eggs of chromatic and metallic dragons. One story holds that these eggs were blessed by the dragon gods Bahamut and Tiamat, who wanted to populate the multiverse with people created in their image. Another story claims that dragons created the first dragonborn without the gods’ blessings. Whatever their origin, dragonborn have made homes for themselves on the Material Plane. Dragonborn look like wingless, bipedal dragons—scaly, bright-eyed, and thick-boned with horns on their heads—and their coloration and other features are reminiscent of their draconic ancestors.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
    variant: null,
  },
  {
    id: 3,
    slug: "dwarf",
    defaultName: "Dwarf",
    defaultDescription: `Dwarves were raised from the earth in the elder days by a deity of the forge. Called by various names on different worlds—Moradin, Reorx, and others—that god gave dwarves an affinity for stone and metal and for living underground. The god also made them resilient like the mountains, with a life span of about 350 years. Squat and often bearded, the original dwarves carved cities and strongholds into mountainsides and under the earth. Their oldest legends tell of conflicts with the monsters of mountaintops and the Underdark, whether those monsters were towering giants or subterranean horrors. Inspired by those tales, dwarves of any culture often sing of valorous deeds—especially of the little overcoming the mighty. On some worlds in the multiverse, the first settlements of dwarves were built in hills or mountains, and the families who trace their ancestry to those settlements call themselves hill dwarves or mountain dwarves, respectively. The Greyhawk and Dragonlance settings have such communities.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
    variant: null,
  },
  {
    slug: "elf",
    defaultName: "Elf",
    defaultDescription: `Created by the god Corellon, the first elves could change their forms at will. They lost this ability when Corellon cursed them for plotting with the deity Lolth, who tried and failed to usurp Corellon’s dominion. When Lolth was cast into the Abyss, most elves renounced her and earned Corellon’s forgiveness, but that which Corellon had taken from them was lost forever. No longer able to shape-shift at will, the elves retreated to the Feywild, where their sorrow was deepened by that plane’s influence. Over time, curiosity led many of them to explore other planes of existence, including worlds in the Material Plane. Elves have pointed ears and lack facial and body hair. They live for around 750 years, and they don’t sleep but instead enter a trance when they need to rest. In that state, they remain aware of their surroundings while immersing themselves in memories and meditations. An environment subtly transforms elves after they inhabit it for a millennium or more, and it grants them certain kinds of magic. Drow, high elves, and wood elves are examples of elves who have been transformed thus.`,
    hasDarkvision: false,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
    variant: null,
  },
];

export const speciesTraitsSeed = [
  {
    speciesId: 1,
    slug: "celestial-resistance",
    defaultName: "Celestial Resistance",
    defaultDescription: `You have Resistance to Necrotic damage and Radiant damage.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "healing-hands",
    defaultName: "Healing Hands",
    defaultDescription: `As a Magic action, you touch a creature and roll a number of d4s equal to your Proficiency Bonus. The creature regains a number of Hit Points equal to the total rolled. Once you use this trait, you can’t use it again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "light-bearer",
    defaultName: "Light Bearer",
    defaultDescription: `You know the Light cantrip. Charisma is your spellcasting ability for it.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "celestial-revelation",
    defaultName: "Celestial Revelation",
    defaultDescription: `When you reach character level 3, you can transform as a Bonus Action using one of the options below (choose the option each time you transform). The transformation lasts for 1 minute or until you end it (no action required). Once you transform, you can’t do so again until you finish a Long Rest. Once on each of your turns before the transformation ends, you can deal extra damage to one target when you deal damage to it with an attack or a spell. The extra damage equals your Proficiency Bonus, and the extra damage’s type is either Necrotic for Necrotic Shroud or Radiant for Heavenly Wings and Inner Radiance. Here are the transformation options:`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "heavenly-wings",
    defaultName: "Heavenly Wings",
    defaultDescription: `Two spectral wings sprout from your back temporarily. Until the transformation ends, you have a Fly Speed equal to your Speed.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "inner-radiance",
    defaultName: "Inner Radiance",
    defaultDescription: `Searing light temporarily radiates from your eyes and mouth. For the duration, you shed Bright Light in a 10-foot radius and Dim Light for an additional 10 feet, and at the end of each of your turns, each creature within 10 feet of you takes Radiant damage equal to your Proficiency Bonus.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "necrotic-shroud",
    defaultName: "Necrotic Shroud",
    defaultDescription: `Your eyes briefly become pools of darkness, and flightless wings sprout from your back temporarily. Creatures other than your allies within 10 feet of you must succeed on a Charisma saving throw (DC 8 plus your Charisma modifier and Proficiency Bonus) or have the Frightened condition until the end of your next turn.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "draconic-ancestry",
    defaultName: "Draconic Ancestry",
    defaultDescription: `Your lineage stems from a dragon progenitor. Choose the kind of dragon from the Draconic Ancestors table. Your choice affects your Breath Weapon and Damage Resistance traits as well as your appearance. Draconic Ancestors: Black / Copper → Acid Blue / Bronze → Lightning Brass / Gold / Red → Fire Green → Poison Silver / White → Cold`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "breath-weapon",
    defaultName: "Breath Weapon",
    defaultDescription: `When you take the Attack action on your turn, you can replace one of your attacks with an exhalation of magical energy in either a 15-foot Cone or a 30-foot Line that is 5 feet wide (choose the shape each time). Each creature in that area must make a Dexterity saving throw (DC 8 + your Constitution modifier and Proficiency Bonus). On a failed save, a creature takes 1d10 damage of the type determined by your Draconic Ancestry trait. On a successful save, a creature takes half as much damage. This damage increases by 1d10 when you reach character levels 5 (2d10), 11 (3d10), and 17 (4d10).

You can use this Breath Weapon a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "damage-resistance",
    defaultName: "Damage Resistance",
    defaultDescription: `You have Resistance to the damage type determined by your Draconic Ancestry trait.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "draconic-flight",
    defaultName: "Draconic Flight",
    defaultDescription: `When you reach character level 5, you can channel draconic magic to give yourself temporary flight. As a Bonus Action, you sprout spectral wings on your back that last for 10 minutes or until you retract the wings (no action required) or have the Incapacitated condition. During that time, you have a Fly Speed equal to your Speed. Your wings appear to be made of the same energy as your Breath Weapon. Once you use this trait, you can’t use it again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 120 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "dwarven-resilience",
    defaultName: "Dwarven Resilience",
    defaultDescription: `You have Resistance to Poison damage. You also have Advantage on saving throws you make to avoid or end the Poisoned condition.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "dwarven-toughness",
    defaultName: "Dwarven Toughness",
    defaultDescription: `Your Hit Point maximum increases by 1, and it increases by 1 again whenever you gain a level.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "stonecunning",
    defaultName: "Stonecunning",
    defaultDescription: `As a Bonus Action, you gain Tremorsense with a range of 60 feet for 10 minutes. You must be on a stone surface or touching a stone surface to use this Tremorsense. The stone can be natural or worked.

You can use this Bonus Action a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
];
