import { SYSTEM_ID_DD5E } from "../constants";

export const speciesSeed = [
  {
    slug: "aasimar",
    defaultName: "Aasimar",
    defaultDescription: `Aasimar (pronounced AH-sih-mar) are mortals who carry a spark of the Upper Planes within their souls. Whether descended from an angelic being or infused with celestial power, they can fan that spark to bring light, healing, and heavenly fury. Aasimar can arise among any population of mortals. They resemble their parents, but they live for up to 160 years and have features that hint at their celestial heritage, such as metallic freckles, luminous eyes, a halo, or the skin color of an angel (silver, opalescent green, or coppery red). These features start subtle and become obvious when the aasimar learns to reveal their full celestial nature.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "dragonborn",
    defaultName: "Dragonborn",
    defaultDescription: `The ancestors of dragonborn hatched from the eggs of chromatic and metallic dragons. One story holds that these eggs were blessed by the dragon gods Bahamut and Tiamat, who wanted to populate the multiverse with people created in their image. Another story claims that dragons created the first dragonborn without the gods’ blessings. Whatever their origin, dragonborn have made homes for themselves on the Material Plane. Dragonborn look like wingless, bipedal dragons—scaly, bright-eyed, and thick-boned with horns on their heads—and their coloration and other features are reminiscent of their draconic ancestors.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    id: 3,
    slug: "dwarf",
    defaultName: "Dwarf",
    defaultDescription: `Dwarves were raised from the earth in the elder days by a deity of the forge. Called by various names on different worlds—Moradin, Reorx, and others—that god gave dwarves an affinity for stone and metal and for living underground. The god also made them resilient like the mountains, with a life span of about 350 years. Squat and often bearded, the original dwarves carved cities and strongholds into mountainsides and under the earth. Their oldest legends tell of conflicts with the monsters of mountaintops and the Underdark, whether those monsters were towering giants or subterranean horrors. Inspired by those tales, dwarves of any culture often sing of valorous deeds—especially of the little overcoming the mighty. On some worlds in the multiverse, the first settlements of dwarves were built in hills or mountains, and the families who trace their ancestry to those settlements call themselves hill dwarves or mountain dwarves, respectively. The Greyhawk and Dragonlance settings have such communities.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "elf",
    defaultName: "Elf",
    defaultDescription: `Created by the god Corellon, the first elves could change their forms at will. They lost this ability when Corellon cursed them for plotting with the deity Lolth, who tried and failed to usurp Corellon’s dominion. When Lolth was cast into the Abyss, most elves renounced her and earned Corellon’s forgiveness, but that which Corellon had taken from them was lost forever. No longer able to shape-shift at will, the elves retreated to the Feywild, where their sorrow was deepened by that plane’s influence. Over time, curiosity led many of them to explore other planes of existence, including worlds in the Material Plane. Elves have pointed ears and lack facial and body hair. They live for around 750 years, and they don’t sleep but instead enter a trance when they need to rest. In that state, they remain aware of their surroundings while immersing themselves in memories and meditations. An environment subtly transforms elves after they inhabit it for a millennium or more, and it grants them certain kinds of magic. Drow, high elves, and wood elves are examples of elves who have been transformed thus.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "gnome",
    defaultName: "Gnome",
    defaultDescription: `Gnomes are magical folk created by gods of invention, illusions, and life underground. The earliest gnomes were seldom seen by other folk due to the gnomes’ secretive nature and their propensity for living in forests and burrows. What they lacked in size, they made up for in cleverness. They confounded predators with traps and labyrinthine tunnels. They also learned magic from gods like Garl Glittergold, Baervan Wildwanderer, and Baravar Cloakshadow, who visited them in disguise. That magic eventually created the lineages of forest gnomes and rock gnomes. Gnomes are petite folk with big eyes and pointed ears, who live around 425 years. Many gnomes like the feeling of a roof over their head, even if that “roof” is nothing more than a hat.`,
    hasDarkvision: true,
    speed: 30,
    size: "small",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "goliath",
    defaultName: "Goliath",
    defaultDescription: `Towering over most folk, goliaths are distant descendants of giants. Each goliath bears the favors of the first giants—favors that manifest in various supernatural boons, including the ability to quickly grow and temporarily approach the height of goliaths' gigantic kin. Goliaths have physical characteristics that are reminiscent of the giants in their family lines. For example, some goliaths look like stone giants, while others resemble fire giants. Whatever giants they count as kin, goliaths have forged their own path in the multiverse—unencumbered by the internecine conflicts that have ravaged giantkind for ages—and seek heights above those reached by their ancestors.`,
    hasDarkvision: false,
    speed: 35,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "halfling",
    defaultName: "Halfling",
    defaultDescription: `Cherished and guided by gods who value life, home, and hearth, halflings gravitate toward bucolic havens where family and community help shape their lives. That said, many halflings possess a brave and adventurous spirit that leads them on journeys of discovery, affording them the chance to explore a bigger world and make new friends along the way. Their size—similar to that of a human child—helps them pass through crowds unnoticed and slip through tight spaces. Anyone who has spent time around halflings, particularly halfling adventurers, has likely witnessed the storied "luck of the halflings" in action. When a halfling is in mortal danger, an unseen force seems to intervene on the halfling's behalf. Many halflings believe in the power of luck, and they attribute their unusual gift to one or more of their benevolent gods, including Yondalla, Brandobaris, and Charmalaine. The same gift might contribute to their robust life spans (about 150 years). Halfling communities come in all varieties. For every sequestered shire tucked away in an unspoiled part of the world, there’s a crime syndicate like the Boromar Clan in the Eberron setting or a territorial mob of halflings like those in the Dark Sun setting.`,
    hasDarkvision: false,
    speed: 30,
    size: "small",
    systemId: SYSTEM_ID_DD5E,
    variant: null,
  },
  {
    slug: "human",
    defaultName: "Human",
    defaultDescription: `Found throughout the multiverse, humans are as varied as they are numerous, and they endeavor to achieve as much as they can in the years they are given. Their ambition and resourcefulness are commended, respected, and feared on many worlds. Humans are as diverse in appearance as the people of Earth, and they have many gods. Scholars dispute the origin of humanity, but one of the earliest known human gatherings is said to have occurred in Sigil, the torus-shaped city at the center of the multiverse and the place where the Common language was born. From there, humans could have spread to every part of the multiverse, bringing the City of Doors’ cosmopolitanism with them.`,
    hasDarkvision: false,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "orc",
    defaultName: "Orc",
    defaultDescription: `Orcs trace their creation to Gruumsh, a powerful god who roamed the wide open spaces of the Material Plane. Gruumsh equipped his children with gifts to help them wander great plains, vast caverns, and churning seas and to face the monsters that lurk there. Even when they turn their devotion to other gods, orcs retain Gruumsh’s gifts: endurance, determination, and the ability to see in darkness. Orcs are, on average, tall and broad. They have gray skin, ears that are sharply pointed, and prominent lower canines that resemble small tusks. Orc youths on some worlds are told about their ancestors' great travels and travails. Inspired by those tales, many of those orcs wonder when Gruumsh will call on them to match the heroic deeds of old and if they will prove worthy of his favor. Other orcs are happy to leave old tales in the past and find their own way.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "tiefling",
    defaultName: "Tiefling",
    defaultDescription: `Tieflings are either born in the Lower Planes or have fiendish ancestors who originated there. A tiefling (pronounced TEE-fling) is linked by blood to a devil, a demon, or some other Fiend. This connection to the Lower Planes is the tiefling’s fiendish legacy, which comes with the promise of power yet has no effect on the tiefling’s moral outlook. A tiefling chooses whether to embrace or lament their fiendish legacy. The three legacies are Abyssal, Chthonic, and Infernal.`,
    hasDarkvision: true,
    speed: 30,
    size: "medium",
    systemId: SYSTEM_ID_DD5E,
  },
];

export const speciesTraitsSeed = [
  {
    speciesId: 1,
    slug: "celestial-resistance",
    defaultName: "Celestial Resistance",
    defaultDescription: `You have Resistance to Necrotic damage and Radiant damage.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "healing-hands",
    defaultName: "Healing Hands",
    defaultDescription: `As a Magic action, you touch a creature and roll a number of d4s equal to your Proficiency Bonus. The creature regains a number of Hit Points equal to the total rolled. Once you use this trait, you can’t use it again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "light-bearer",
    defaultName: "Light Bearer",
    defaultDescription: `You know the Light cantrip. Charisma is your spellcasting ability for it.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "celestial-revelation",
    defaultName: "Celestial Revelation",
    defaultDescription: `When you reach character level 3, you can transform as a Bonus Action using one of the options below (choose the option each time you transform). The transformation lasts for 1 minute or until you end it (no action required). Once you transform, you can’t do so again until you finish a Long Rest. Once on each of your turns before the transformation ends, you can deal extra damage to one target when you deal damage to it with an attack or a spell. The extra damage equals your Proficiency Bonus, and the extra damage’s type is either Necrotic for Necrotic Shroud or Radiant for Heavenly Wings and Inner Radiance. Here are the transformation options:`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "heavenly-wings",
    defaultName: "Heavenly Wings",
    defaultDescription: `Two spectral wings sprout from your back temporarily. Until the transformation ends, you have a Fly Speed equal to your Speed.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "inner-radiance",
    defaultName: "Inner Radiance",
    defaultDescription: `Searing light temporarily radiates from your eyes and mouth. For the duration, you shed Bright Light in a 10-foot radius and Dim Light for an additional 10 feet, and at the end of each of your turns, each creature within 10 feet of you takes Radiant damage equal to your Proficiency Bonus.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 1,
    slug: "necrotic-shroud",
    defaultName: "Necrotic Shroud",
    defaultDescription: `Your eyes briefly become pools of darkness, and flightless wings sprout from your back temporarily. Creatures other than your allies within 10 feet of you must succeed on a Charisma saving throw (DC 8 plus your Charisma modifier and Proficiency Bonus) or have the Frightened condition until the end of your next turn.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "draconic-ancestry",
    defaultName: "Draconic Ancestry",
    defaultDescription: `Your lineage stems from a dragon progenitor. Choose the kind of dragon from the Draconic Ancestors table. Your choice affects your Breath Weapon and Damage Resistance traits as well as your appearance. Draconic Ancestors: Black / Copper → Acid Blue / Bronze → Lightning Brass / Gold / Red → Fire Green → Poison Silver / White → Cold`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "breath-weapon",
    defaultName: "Breath Weapon",
    defaultDescription: `When you take the Attack action on your turn, you can replace one of your attacks with an exhalation of magical energy in either a 15-foot Cone or a 30-foot Line that is 5 feet wide (choose the shape each time). Each creature in that area must make a Dexterity saving throw (DC 8 + your Constitution modifier and Proficiency Bonus). On a failed save, a creature takes 1d10 damage of the type determined by your Draconic Ancestry trait. On a successful save, a creature takes half as much damage. This damage increases by 1d10 when you reach character levels 5 (2d10), 11 (3d10), and 17 (4d10).

You can use this Breath Weapon a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "damage-resistance",
    defaultName: "Damage Resistance",
    defaultDescription: `You have Resistance to the damage type determined by your Draconic Ancestry trait.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 2,
    slug: "draconic-flight",
    defaultName: "Draconic Flight",
    defaultDescription: `When you reach character level 5, you can channel draconic magic to give yourself temporary flight. As a Bonus Action, you sprout spectral wings on your back that last for 10 minutes or until you retract the wings (no action required) or have the Incapacitated condition. During that time, you have a Fly Speed equal to your Speed. Your wings appear to be made of the same energy as your Breath Weapon. Once you use this trait, you can’t use it again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 120 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "dwarven-resilience",
    defaultName: "Dwarven Resilience",
    defaultDescription: `You have Resistance to Poison damage. You also have Advantage on saving throws you make to avoid or end the Poisoned condition.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "dwarven-toughness",
    defaultName: "Dwarven Toughness",
    defaultDescription: `Your Hit Point maximum increases by 1, and it increases by 1 again whenever you gain a level.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 3,
    slug: "stonecunning",
    defaultName: "Stonecunning",
    defaultDescription: `As a Bonus Action, you gain Tremorsense with a range of 60 feet for 10 minutes. You must be on a stone surface or touching a stone surface to use this Tremorsense. The stone can be natural or worked. You can use this Bonus Action a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 4,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 4,
    slug: "elven-lineage",
    defaultName: "Elven Lineage",
    defaultDescription: `You are part of a lineage that grants you supernatural abilities. Choose a lineage from the Elven Lineages table. You gain the level 1 benefit of that lineage. When you reach character levels 3 and 5, you learn a higher-level spell, as shown on the table. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have of the appropriate level. Intelligence, Wisdom, or Charisma is your spellcasting ability for the spells you cast with this trait (choose the ability when you select the lineage).`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 4,
    slug: "fey-ancestry",
    defaultName: "Fey Ancestry",
    defaultDescription: `You have Advantage on saving throws you make to avoid or end the Charmed condition.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 4,
    slug: "keen-senses",
    defaultName: "Keen Senses",
    defaultDescription: `You have proficiency in the Insight, Perception, or Survival skill.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 4,
    slug: "trance",
    defaultName: "Trance",
    defaultDescription: `You don’t need to sleep, and magic can’t put you to sleep. You can finish a Long Rest in 4 hours if you spend those hours in a trancelike meditation, during which you retain consciousness.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 5,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 5,
    slug: "gnomish-cunning",
    defaultName: "Gnomish Cunning",
    defaultDescription: `You have Advantage on Intelligence, Wisdom, and Charisma saving throws.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 5,
    slug: "gnomish-lineage",
    defaultName: "Gnomish Lineage",
    defaultDescription: `You are part of a lineage that grants you supernatural abilities. Choose one of the following options: Forest Gnome or Rock Gnome.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 6,
    slug: "giant-ancestry",
    defaultName: "Giant Ancestry",
    defaultDescription: `You are descended from Giants. Choose one of the following supernatural boons from your ancestry: Cloud, Fire, Frost, Hill, Stone, or Storm. You can use the chosen benefit a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 6,
    slug: "large-form",
    defaultName: "Large Form",
    defaultDescription: `Starting at character level 5, you can change your size to Large as a Bonus Action if you're in a big enough space. This transformation lasts for 10 minutes or until you end it (no action required). During that time, you have Advantage on Strength checks, and your Speed increases by 10 feet. Once you use this trait, you can’t use it again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 6,
    slug: "powerful-build",
    defaultName: "Powerful Build",
    defaultDescription: `You have Advantage on any saving throw you make to end the Grappled condition. You also count as one size larger when determining your carrying capacity.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 7,
    slug: "brave",
    defaultName: "Brave",
    defaultDescription: `You have Advantage on saving throws you make to avoid or end the Frightened condition.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 7,
    slug: "halfling-nimbleness",
    defaultName: "Halfling Nimbleness",
    defaultDescription: `You can move through the space of any creature that is a size larger than you, but you can’t stop in the same space.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 7,
    slug: "luck",
    defaultName: "Luck",
    defaultDescription: `When you roll a 1 on the d20 of a D20 Test, you can reroll the die, and you must use the new roll.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 7,
    slug: "naturally-stealthy",
    defaultName: "Naturally Stealthy",
    defaultDescription: `You can take the Hide action even when you are obscured only by a creature that is at least one size larger than you.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 8,
    slug: "resourceful",
    defaultName: "Resourceful",
    defaultDescription: `You gain Heroic Inspiration whenever you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 8,
    slug: "skillful",
    defaultName: "Skillful",
    defaultDescription: `You gain proficiency in one skill of your choice.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 8,
    slug: "versatile",
    defaultName: "Versatile",
    defaultDescription: `You gain an Origin feat of your choice (see chapter 5). Skilled is recommended.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 9,
    slug: "adrenaline-rush",
    defaultName: "Adrenaline Rush",
    defaultDescription: `You can take the Dash action as a Bonus Action. When you do so, you gain a number of Temporary Hit Points equal to your Proficiency Bonus. You can use this trait a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Short or Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 9,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 120 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 9,
    slug: "relentless-endurance",
    defaultName: "Relentless Endurance",
    defaultDescription: `When you are reduced to 0 Hit Points but not killed outright, you can drop to 1 Hit Point instead. Once you use this trait, you can’t do so again until you finish a Long Rest.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 10,
    slug: "darkvision",
    defaultName: "Darkvision",
    defaultDescription: `You have Darkvision with a range of 60 feet.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 10,
    slug: "fiendish-legacy",
    defaultName: "Fiendish Legacy",
    defaultDescription: `You are the recipient of a legacy that grants you supernatural abilities. Choose a legacy from the Fiendish Legacies table. You gain the level 1 benefit of the chosen legacy. When you reach character levels 3 and 5, you learn a higher-level spell, as shown on the table. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have of the appropriate level. Intelligence, Wisdom, or Charisma is your spellcasting ability for the spells (choose when you select your legacy).`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    speciesId: 10,
    slug: "otherworldly-presence",
    defaultName: "Otherworldly Presence",
    defaultDescription: `You know the Thaumaturgy cantrip. When you cast it with this trait, the spell uses the same spellcasting ability you use for your Fiendish Legacy trait.`,
    systemId: SYSTEM_ID_DD5E,
  },
];

export const subspeciesSeed = [
  // === DRAGONBORN ANCESTRIES ===
  {
    slug: "black-dragonborn",
    speciesId: 2,
    defaultName: "Black Dragonborn",
    defaultDescription:
      "Descended from black dragons. Breath Weapon & Resistance: Acid.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "blue-dragonborn",
    speciesId: 2,
    defaultName: "Blue Dragonborn",
    defaultDescription:
      "Descended from blue dragons. Breath Weapon & Resistance: Lightning.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "brass-dragonborn",
    speciesId: 2,
    defaultName: "Brass Dragonborn",
    defaultDescription:
      "Descended from brass dragons. Breath Weapon & Resistance: Fire.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "bronze-dragonborn",
    speciesId: 2,
    defaultName: "Bronze Dragonborn",
    defaultDescription:
      "Descended from bronze dragons. Breath Weapon & Resistance: Lightning.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "copper-dragonborn",
    speciesId: 2,
    defaultName: "Copper Dragonborn",
    defaultDescription:
      "Descended from copper dragons. Breath Weapon & Resistance: Acid.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "gold-dragonborn",
    speciesId: 2,
    defaultName: "Gold Dragonborn",
    defaultDescription:
      "Descended from gold dragons. Breath Weapon & Resistance: Fire.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "green-dragonborn",
    speciesId: 2,
    defaultName: "Green Dragonborn",
    defaultDescription:
      "Descended from green dragons. Breath Weapon & Resistance: Poison.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "red-dragonborn",
    speciesId: 2,
    defaultName: "Red Dragonborn",
    defaultDescription:
      "Descended from red dragons. Breath Weapon & Resistance: Fire.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "silver-dragonborn",
    speciesId: 2,
    defaultName: "Silver Dragonborn",
    defaultDescription:
      "Descended from silver dragons. Breath Weapon & Resistance: Cold.",
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "white-dragonborn",
    speciesId: 2,
    defaultName: "White Dragonborn",
    defaultDescription:
      "Descended from white dragons. Breath Weapon & Resistance: Cold.",
    systemId: SYSTEM_ID_DD5E,
  },
  // === ELF VARIANTS ===
  {
    slug: "drow",
    speciesId: 4,
    defaultName: "Drow",
    defaultDescription: `Drow typically dwell in the Underdark and have been shaped by it. Some drow individuals and societies avoid the Underdark altogether yet carry its magic. In the Eberron setting, for example, drow dwell in rainforests and cyclopean ruins on the continent of Xen’drik.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "high-elf",
    speciesId: 4,
    defaultName: "High Elf",
    defaultDescription: `High elves have been infused with the magic of crossings between the Feywild and the Material Plane. On some worlds, high elves refer to themselves by other names. For example, they call themselves sun or moon elves in the Forgotten Realms setting, Silvanesti and Qualinesti in the Dragonlance setting, and Aereni in the Eberron setting.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "wood-elf",
    speciesId: 4,
    defaultName: "Wood Elf",
    defaultDescription: `Wood elves carry the magic of primeval forests within themselves. They are known by many other names, including wild elves, green elves, and forest elves. Grugach are reclusive wood elves of the Greyhawk setting, while the Kagonesti and the Tairnadal are wood elves of the Dragonlance and Eberron settings, respectively.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "forest-gnome",
    speciesId: 5, // assuming gnome is 5th species
    defaultName: "Forest Gnome",
    defaultDescription: `You know the Minor Illusion cantrip. You also always have the Speak with Animals spell prepared. You can cast it without a spell slot a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a Long Rest. You can also use any spell slots you have to cast the spell.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "rock-gnome",
    speciesId: 5,
    defaultName: "Rock Gnome",
    defaultDescription: `You know the Mending and Prestidigitation cantrips. In addition, you can spend 10 minutes casting Prestidigitation to create a Tiny clockwork device (AC 5, 1 HP), such as a toy, fire starter, or music box. The device produces an effect whenever you or another creature takes a Bonus Action to activate it with a touch. If the chosen effect has options, you choose one when you create the device. You can have up to 3 such devices at once, and each falls apart 8 hours after its creation or when you dismantle it with a Utilize action.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "cloud-giant-goliath",
    speciesId: 6,
    defaultName: "Cloud Giant Ancestry",
    defaultDescription: `Cloud’s Jaunt: As a Bonus Action, you magically teleport up to 30 feet to an unoccupied space you can see.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "fire-giant-goliath",
    speciesId: 6,
    defaultName: "Fire Giant Ancestry",
    defaultDescription: `Fire’s Burn: When you hit a target with an attack roll and deal damage to it, you can also deal 1d10 Fire damage to that target.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "frost-giant-goliath",
    speciesId: 6,
    defaultName: "Frost Giant Ancestry",
    defaultDescription: `Frost’s Chill: When you hit a target with an attack roll and deal damage to it, you can also deal 1d6 Cold damage and reduce its Speed by 10 feet until the start of your next turn.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "hill-giant-goliath",
    speciesId: 6,
    defaultName: "Hill Giant Ancestry",
    defaultDescription: `Hill’s Tumble: When you hit a Large or smaller creature with an attack roll and deal damage to it, you can give that target the Prone condition.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "stone-giant-goliath",
    speciesId: 6,
    defaultName: "Stone Giant Ancestry",
    defaultDescription: `Stone’s Endurance: When you take damage, you can take a Reaction to roll 1d12. Add your Constitution modifier to the number rolled and reduce the damage by that total.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "storm-giant-goliath",
    speciesId: 6,
    defaultName: "Storm Giant Ancestry",
    defaultDescription: `Storm’s Thunder: When you take damage from a creature within 60 feet of you, you can take a Reaction to deal 1d8 Thunder damage to that creature.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "strongheart-halfling",
    speciesId: 7,
    defaultName: "Strongheart Halfling",
    defaultDescription: `Halflings who prefer to live underground are sometimes called strongheart halflings or stouts.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "lightfoot-halfling",
    speciesId: 7,
    defaultName: "Lightfoot Halfling",
    defaultDescription: `Nomadic halflings, as well as those who live among humans and other tall folk, are sometimes called lightfoot halflings or tallfellows.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "abyssal-tiefling",
    speciesId: 10,
    defaultName: "Abyssal Tiefling",
    defaultDescription: `The entropy of the Abyss, the chaos of Pandemonium, and the despair of Carceri call to tieflings who have the abyssal legacy. Horns, fur, tusks, and peculiar scents are common physical features of such tieflings, most of whom have the blood of demons coursing through their veins.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "chthonic-tiefling",
    speciesId: 10,
    defaultName: "Chthonic Tiefling",
    defaultDescription: `Tieflings who have the chthonic legacy feel not only the tug of Carceri but also the greed of Gehenna and the gloom of Hades. Some of these tieflings look cadaverous. Others possess the unearthly beauty of a succubus, or they have physical features in common with a night hag, a yugoloth, or some other Neutral Evil fiendish ancestor.`,
    systemId: SYSTEM_ID_DD5E,
  },
  {
    slug: "infernal-tiefling",
    speciesId: 10,
    defaultName: "Infernal Tiefling",
    defaultDescription: `The infernal legacy connects tieflings not only to Gehenna but also the Nine Hells and the raging battlefields of Acheron. Horns, spines, tails, golden eyes, and a faint odor of sulfur or smoke are common physical features of such tieflings, most of whom trace their ancestry to devils.`,
    systemId: SYSTEM_ID_DD5E,
  },
];
