import {
  hitDiceEnum,
  weaponDamageTypeEnum,
  weaponMasteryEnum,
  weaponPropertyEnum,
  weapons,
  weaponTypeEnum,
} from "@/db/schema";
import { z } from "zod";

const weaponSchema = z.object({
  slug: z.string().min(1).max(100),
  defaultName: z.string().min(1).max(200),
  defaultDamageDice: z.enum(hitDiceEnum.enumValues),
  secondaryDamageDice: z.enum(hitDiceEnum.enumValues).optional(),
  weaponType: z.enum(weaponTypeEnum.enumValues),
  weaponProperties: z.array(z.enum(weaponPropertyEnum.enumValues)),
  weaponMastery: z.enum(weaponMasteryEnum.enumValues),
  damageType: z.enum(weaponDamageTypeEnum.enumValues),
  range: z.object({ min: z.number(), max: z.number() }).optional(),
  weight: z.number().min(0).max(1000),
  value: z.number().min(0).max(200_000),
  systemId: z.number(),
});

type WeaponInsertSchema = typeof weapons.$inferInsert;

const weaponsSeedData: WeaponInsertSchema[] = [
  {
    slug: "club",
    defaultName: "Club",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "slow",
    systemId: 1,
    weight: 2.0,
    value: 10,
    weaponProperties: ["light"],
    damageType: "bludgeoning",
    range: null,
  },
  {
    slug: "dagger",
    defaultName: "Dagger",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "nick",
    systemId: 1,
    weight: 1.0,
    value: 200,
    weaponProperties: ["finesse", "light", "thrown"],
    damageType: "piercing",
    range: {
      min: 20,
      max: 60,
    },
  },
  {
    slug: "greatclub",
    defaultName: "Greatclub",
    defaultDamageDice: "d8",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "push",
    systemId: 1,
    weight: 10.0,
    value: 20,
    weaponProperties: ["two-handed"],
    damageType: "bludgeoning",
    range: null,
  },
  {
    slug: "handaxe",
    defaultName: "Handaxe",
    defaultDamageDice: "d6",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "vex",
    systemId: 1,
    weight: 2.0,
    value: 500,
    weaponProperties: ["light", "thrown"],
    damageType: "slashing",
    range: {
      min: 20,
      max: 60,
    },
  },
  {
    slug: "javelin",
    defaultName: "Javelin",
    defaultDamageDice: "d6",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "slow",
    systemId: 1,
    weight: 2.0,
    value: 50,
    weaponProperties: ["thrown"],
    damageType: "piercing",
    range: {
      min: 30,
      max: 120,
    },
  },
  {
    slug: "light-hammer",
    defaultName: "Light Hammer",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "nick",
    systemId: 1,
    weight: 2.0,
    value: 200,
    weaponProperties: ["light", "thrown"],
    damageType: "bludgeoning",
    range: {
      min: 20,
      max: 60,
    },
  },
  {
    slug: "mace",
    defaultName: "Mace",
    defaultDamageDice: "d6",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "sap",
    systemId: 1,
    weight: 4.0,
    value: 500,
    weaponProperties: [],
    damageType: "bludgeoning",
    range: null,
  },
  {
    slug: "quarterstaff",
    defaultName: "Quarterstaff",
    defaultDamageDice: "d6",
    secondaryDamageDice: "d8",
    weaponType: "simple",
    weaponMastery: "topple",
    systemId: 1,
    weight: 4.0,
    value: 20,
    weaponProperties: ["versatile"],
    damageType: "bludgeoning",
    range: null,
  },
  {
    slug: "sickle",
    defaultName: "Sickle",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "nick",
    systemId: 1,
    weight: 2.0,
    value: 100,
    weaponProperties: ["light"],
    damageType: "slashing",
    range: null,
  },
  {
    slug: "spear",
    defaultName: "Spear",
    defaultDamageDice: "d6",
    secondaryDamageDice: "d8",
    weaponType: "simple",
    weaponMastery: "sap",
    systemId: 1,
    weight: 3.0,
    value: 100,
    weaponProperties: ["thrown", "versatile"],
    damageType: "piercing",
    range: {
      min: 20,
      max: 60,
    },
  },
  {
    slug: "dart",
    defaultName: "Dart",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "vex",
    systemId: 1,
    weight: 0.25,
    value: 5,
    weaponProperties: ["finesse", "thrown"],
    damageType: "piercing",
    range: {
      min: 20,
      max: 60,
    },
  },
  {
    slug: "light-crossbow",
    defaultName: "Light Crossbow",
    defaultDamageDice: "d8",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "slow",
    systemId: 1,
    weight: 5.0,
    value: 2500,
    weaponProperties: ["ammunition", "loading", "two-handed"],
    damageType: "piercing",
    range: {
      min: 80,
      max: 320,
    },
  },
  {
    slug: "shortbow",
    defaultName: "Shortbow",
    defaultDamageDice: "d6",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "vex",
    systemId: 1,
    weight: 2.0,
    value: 2500,
    weaponProperties: ["ammunition", "two-handed"],
    damageType: "piercing",
    range: {
      min: 80,
      max: 320,
    },
  },
  {
    slug: "sling",
    defaultName: "Sling",
    defaultDamageDice: "d4",
    secondaryDamageDice: null,
    weaponType: "simple",
    weaponMastery: "slow",
    systemId: 1,
    weight: 0.0,
    value: 10,
    weaponProperties: ["ammunition"],
    damageType: "bludgeoning",
    range: {
      min: 30,
      max: 120,
    },
  },
];
